AWSTemplateFormatVersion: '2010-09-09'
Description: "WebApp CICD Stack:\n- CodePipeline IAM Role\n- CodeDeploy IAM Role\n\
  - Web App Pipeline\n"
Parameters:
  GitHubConnectionArn:
    Type: String
    Description: ARN of the CodeStar Connection to GitHub
  GitHubRepo:
    Type: String
    Description: GitHub repository name (format 'user/repo')
  GitHubSourceRepo:
    Type: String
    Description: GitHub repository URL
  GitHubBranch:
    Type: String
    Description: GitHub branch name
  ArtifactBucketName:
    Type: String
Resources:
  CodeBuildImageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/intermodelity-app-cfn-artifact-20240308172959/cicd-package/32f1951cc20039dcdb3ff6f0c170da7b.template
      Parameters:
        GitHubSourceRepo:
          Ref: GitHubSourceRepo
        GitHubBranchName:
          Ref: GitHubBranch
        ArtifactBucketName:
          Ref: ArtifactBucketName
  CodeDeployStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/intermodelity-app-cfn-artifact-20240308172959/cicd-package/b4930bf6f67522d4a3090b4659e35946.template
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName:
          Fn::Sub: ${AWS::StackName}CodePipelinePolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action:
            - s3:*
            - ec2:*
            - autoscaling:*
            - codedeploy:*
            - codebuild:*
            - ecr:*
            - elasticloadbalancing:*
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - cloudformation:*
            - iam:PassRole
            - iam:CreateRole
            - iam:DetachRolePolicy
            - iam:DeleteRolePolicy
            - iam:PutRolePolicy
            - iam:DeleteRole
            - iam:AttachRolePolicy
            - iam:GetRole
            Effect: Allow
            Resource: '*'
          - Action:
            - codestar-connections:UseConnection
            Effect: Allow
            Resource:
              Ref: GitHubConnectionArn
  MyPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Fn::GetAtt:
        - CodePipelineRole
        - Arn
      ArtifactStore:
        Type: S3
        Location:
          Ref: ArtifactBucketName
      Stages:
      - Name: Source
        Actions:
        - Name: GitHub_Source
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: '1'
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceArtifact
          Configuration:
            ConnectionArn:
              Ref: GitHubConnectionArn
            FullRepositoryId:
              Ref: GitHubRepo
            BranchName:
              Ref: GitHubBranch
            OutputArtifactFormat: CODEBUILD_CLONE_REF
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: BuildContainerImage
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          InputArtifacts:
          - Name: SourceArtifact
          OutputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ProjectName:
              Fn::GetAtt:
              - CodeBuildImageStack
              - Outputs.CodeBuildProjectName
          RunOrder: 1
      - Name: Deploy
        Actions:
        - Name: CodeDeploy
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Version: '1'
            Provider: CodeDeploy
          InputArtifacts:
          - Name: BuildArtifact
          Configuration:
            ApplicationName:
              Fn::GetAtt:
              - CodeDeployStack
              - Outputs.CodeDeployApplicationName
            DeploymentGroupName:
              Fn::GetAtt:
              - CodeDeployStack
              - Outputs.CodeDeployDeploymentGroupName
          RunOrder: 1
